services:
  clojure-service:
    platform: linux/amd64
    build: ./
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres-database
    links:
      - postgres-database

  postgres-database:
    image: postgres:15.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local